Swagger search
devops-golf-s17/wishlists pull request #125
Opened 2017-05-02 22:21 UTC by BobZcao

Please let me if I need to change anything.

2017-05-02 22:33 UTC, xynazog requested changes
The display is like this
```
{
Search results for keyword "iPhone" in wishlists with user ID "user3": [
{
Results from wishlist with ID: 3: [
{
description: "Product (Red) iPhone 7 Plus 256 GB",
item_id: "a12"
}
]
}
]
}
```
Your search shows
```
[
  {
    "wishlist_item_id": {
      "item_description": "string",
      "item_id": "string"
    }
  }
]
```

2017-05-02 22:37 UTC, BobZcao commented
I see, I will fix it, thank you @xynazog

2017-05-02 22:56 UTC, pinocchiochang commented on app/server.py
> +        description: userid is missing
Please make sure the format is consistent.

2017-05-02 22:56 UTC, pinocchiochang requested changes
As comment.

2017-05-03 01:36 UTC, BobZcao commented
palak will take care of the colon. I set the module schema manually because it is only for documentation instead of the real database.

2017-05-03 02:03 UTC, xynazog reviewed
Looks great! Can you just remove the keywords like iPhone and all? And the example tags?
It would help with the consistency throughout the docs. Approved as soon as it's done 👍

2017-05-03 02:04 UTC, palakbhasin requested changes
In search, query is optional and userid is required.

2017-05-03 03:26 UTC, BobZcao commented
fixed errors according to your suggestions

2017-05-03 03:31 UTC, palakbhasin approved these changes

2017-05-03 03:31 UTC, pinocchiochang approved these changes
Just the format issue.

2017-05-03 03:31 UTC, pinocchiochang commented on app/server.py
> +        description: userid is missing
The format is chaos. I will fix tomorrow.

2017-05-03 03:32 UTC, merged